name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    runs-on: ubuntu-latest
    name: "Unit Tests"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
